version: "3"

services:
  collector:
     build: .
     volumes: 
       - "/datalake/ufmg/telegram:/data"
       - "/datalake/ufmg/telegram/config:/config"
     working_dir: /app

volumes:
  data:
  config:
