version: "3"

services:
  collector:
     build: .
     volumes: 
       - "/home/philipemelo/MPMG_git/data_telegram:/data"
       - "/home/philipemelo/MPMG_git/data_telegram/config:/config"
     working_dir: /app

volumes:
  data:
  config:
